# Generated by Django 5.1.3 on 2025-01-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
