# Generated by Django 5.1.3 on 2025-01-15 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_end_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_start_time',
            field=models.TimeField(default=django.utils.timezone.now, max_length=20),
        ),
    ]
