# Generated by Django 5.1.3 on 2025-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_lending_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_end_time',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_start_time',
            field=models.TimeField(max_length=20),
        ),
    ]
