# Generated by Django 5.1.3 on 2024-11-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lend_count',
            field=models.IntegerField(default=0),
        ),
    ]
