# Generated by Django 5.1.3 on 2024-12-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
    ]
