# Generated by Django 5.1.3 on 2025-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_videoqollanma_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lending',
            name='return_date',
            field=models.DateTimeField(),
        ),
    ]
