# Generated by Django 5.1.3 on 2025-01-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lending_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reason_cancelled',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
