# Generated by Django 5.1.3 on 2025-01-19 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sale_reason_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('director_count', models.PositiveIntegerField(default=0)),
                ('admin_count', models.PositiveIntegerField(default=0)),
                ('seller_count', models.PositiveIntegerField(default=0)),
                ('product_count', models.PositiveIntegerField(default=0)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Ishlayapti'), ('inactive', 'Ishlamayapti')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
