# Generated by Django 5.1.3 on 2025-01-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='category_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
