# Generated by Django 5.1.3 on 2025-01-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tariff_category_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_convicted',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_married',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
