# Generated by Django 5.1.3 on 2025-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_is_convicted_alter_user_is_married'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='scan_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
