# Generated by Django 5.1.3 on 2025-07-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cashwithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Naqd'), ('CARD', 'Karta')], default='CASH', max_length=10),
        ),
    ]
